# ===============================================================================
# FILE PURPOSE:
# Authentication and security utilities for the Hostel Food Management API.
#
# This module provides:
# - Password hashing using bcrypt.
# - Password verification against stored password hashes.
# - JWT access-token creation.
# - JWT token decoding and validation.
#
# SECURITY RULES:
# - Plain-text passwords must never be stored in the database.
# - Passwords are hashed before being persisted.
# - Password verification is performed against the stored password hash.
# - JWT tokens contain the minimum information required to identify the
#   authenticated user.
# - JWT signing uses SECRET_KEY and ALGORITHM from config.py.
#
# CONNECTED FILES & FOLDERS:
# - backend/app/config.py
#       Provides SECRET_KEY, ALGORITHM, and ACCESS_TOKEN_EXP.
#
# - backend/app/models/student.py
#       Stores the password_hash generated by this module.
#
# - backend/app/models/admin.py
#       Stores the password_hash generated by this module.
#
# - backend/app/services/auth_service.py
#       Uses password hashing, verification, and JWT creation during login
#       and authentication.
#
# - backend/app/core/dependencies.py
#       Uses JWT decoding to identify the currently authenticated user.
#
# - backend/app/core/permissions.py
#       Uses the authenticated user's identity/role to enforce access control.
# ===============================================================================

from datetime import datetime, timedelta, timezone

from jose import JWTError, jwt
from passlib.context import CryptContext

from app.config import settings


# Password hashing configuration
pwd_context = CryptContext(
    schemes=["bcrypt"],
    deprecated="auto"
)


def hash_password(password: str) -> str:
    """
    Hash a plain-text password using bcrypt.

    Returns:
        str: Securely hashed password.
    """
    return pwd_context.hash(password)


def verify_password(
    plain_password: str,
    hashed_password: str
) -> bool:
    """
    Verify a plain-text password against a stored password hash.

    Returns:
        bool: True if the password matches, otherwise False.
    """
    return pwd_context.verify(
        plain_password,
        hashed_password
    )


def create_access_token(data: dict, expires_delta: timedelta | None = None) -> str:
    """
    Create a signed JWT access token.

    The token expiration time is determined by expires_delta if provided,
    otherwise by ACCESS_TOKEN_EXP from the application settings.

    Returns:
        str: Encoded JWT access token.
    """

    to_encode = data.copy()

    now = datetime.now(timezone.utc)
    if expires_delta:
        expire = now + expires_delta
    else:
        expire = now + timedelta(
            minutes=settings.ACCESS_TOKEN_EXP
        )

    to_encode.update({
        "iat": now,
        "exp": expire
    })

    return jwt.encode(
        to_encode,
        settings.SECRET_KEY,
        algorithm=settings.ALGORITHM
    )


def decode_access_token(token: str) -> dict:
    """
    Decode and validate a JWT access token.

    Raises:
        JWTError: If the token is invalid, malformed, or expired.

    Returns:
        dict: Decoded JWT payload.
    """

    payload = jwt.decode(
        token,
        settings.SECRET_KEY,
        algorithms=[settings.ALGORITHM]
    )

    return payload